package edu.ynu.travel.mapper.complaint;

import edu.ynu.travel.entity.complaint.ComTypeEntity;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("com_type")
public interface ComTypeEntityMapper {

    List<ComTypeEntity> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_type
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_type
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    int insert(ComTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_type
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    int insertSelective(ComTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_type
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    ComTypeEntity selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_type
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    int updateByPrimaryKeySelective(ComTypeEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table com_type
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    int updateByPrimaryKey(ComTypeEntity record);
}