package edu.ynu.travel.mapper.emergency;

import edu.ynu.travel.entity.emergency.InfoEntity;
import org.springframework.stereotype.Repository;

@Repository("InfoMapper")
public interface InfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    int insert(InfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    int insertSelective(InfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    InfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    int updateByPrimaryKeySelective(InfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table info
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    int updateByPrimaryKey(InfoEntity record);
}