package edu.ynu.travel.entity.hotel;

public class HotelEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_hotel.id
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_hotel.scenic_id
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    private Integer scenicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_hotel.name
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_hotel.type
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_hotel.price
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_hotel.total_room
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    private int totalRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hot_hotel.booked_room
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    private int bookedRoom;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_hotel.id
     *
     * @return the value of hot_hotel.id
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_hotel.id
     *
     * @param id the value for hot_hotel.id
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_hotel.scenic_id
     *
     * @return the value of hot_hotel.scenic_id
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public Integer getScenicId() {
        return scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_hotel.scenic_id
     *
     * @param scenicId the value for hot_hotel.scenic_id
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public void setScenicId(Integer scenicId) {
        this.scenicId = scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_hotel.name
     *
     * @return the value of hot_hotel.name
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_hotel.name
     *
     * @param name the value for hot_hotel.name
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_hotel.type
     *
     * @return the value of hot_hotel.type
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_hotel.type
     *
     * @param type the value for hot_hotel.type
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_hotel.price
     *
     * @return the value of hot_hotel.price
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_hotel.price
     *
     * @param price the value for hot_hotel.price
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_hotel.total_room
     *
     * @return the value of hot_hotel.total_room
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public int getTotalRoom() {
        return totalRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_hotel.total_room
     *
     * @param totalRoom the value for hot_hotel.total_room
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public void setTotalRoom(int totalRoom) {
        this.totalRoom = totalRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hot_hotel.booked_room
     *
     * @return the value of hot_hotel.booked_room
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public int getBookedRoom() {
        return bookedRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hot_hotel.booked_room
     *
     * @param bookedRoom the value for hot_hotel.booked_room
     *
     * @mbggenerated Sun Sep 25 14:17:03 CST 2016
     */
    public void setBookedRoom(int bookedRoom) {
        this.bookedRoom = bookedRoom;
    }
}