package edu.ynu.travel.entity.complaint;

import java.util.Date;

public class ComplaintEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_complaint.id
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_complaint.user_id
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_complaint.reply_com_id
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    private Integer replyComId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_complaint.type
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_complaint.description
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_complaint.create_at
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_complaint.status
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_complaint.id
     *
     * @return the value of com_complaint.id
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_complaint.id
     *
     * @param id the value for com_complaint.id
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_complaint.user_id
     *
     * @return the value of com_complaint.user_id
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_complaint.user_id
     *
     * @param userId the value for com_complaint.user_id
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_complaint.reply_com_id
     *
     * @return the value of com_complaint.reply_com_id
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public Integer getReplyComId() {
        return replyComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_complaint.reply_com_id
     *
     * @param replyComId the value for com_complaint.reply_com_id
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public void setReplyComId(Integer replyComId) {
        this.replyComId = replyComId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_complaint.type
     *
     * @return the value of com_complaint.type
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_complaint.type
     *
     * @param type the value for com_complaint.type
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_complaint.description
     *
     * @return the value of com_complaint.description
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_complaint.description
     *
     * @param description the value for com_complaint.description
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_complaint.create_at
     *
     * @return the value of com_complaint.create_at
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_complaint.create_at
     *
     * @param createAt the value for com_complaint.create_at
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_complaint.status
     *
     * @return the value of com_complaint.status
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_complaint.status
     *
     * @param status the value for com_complaint.status
     *
     * @mbggenerated Wed Sep 07 09:38:59 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}