package edu.ynu.travel.entity.complaint;

public class ComTypeEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_type.type_id
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_type.type_name
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column com_type.description
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_type.type_id
     *
     * @return the value of com_type.type_id
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_type.type_id
     *
     * @param typeId the value for com_type.type_id
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_type.type_name
     *
     * @return the value of com_type.type_name
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_type.type_name
     *
     * @param typeName the value for com_type.type_name
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column com_type.description
     *
     * @return the value of com_type.description
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column com_type.description
     *
     * @param description the value for com_type.description
     *
     * @mbggenerated Tue Sep 20 17:12:19 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}