package edu.ynu.travel.mapper.common;

import edu.ynu.travel.entity.common.ImageEntity;
import org.springframework.stereotype.Repository;

@Repository("ImageMapper")
public interface ImageEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Fri Sep 23 10:32:56 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Fri Sep 23 10:32:56 CST 2016
     */
    int insert(ImageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Fri Sep 23 10:32:56 CST 2016
     */
    int insertSelective(ImageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Fri Sep 23 10:32:56 CST 2016
     */
    ImageEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Fri Sep 23 10:32:56 CST 2016
     */
    int updateByPrimaryKeySelective(ImageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Fri Sep 23 10:32:56 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ImageEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbggenerated Fri Sep 23 10:32:56 CST 2016
     */
    int updateByPrimaryKey(ImageEntity record);
}