package edu.ynu.travel.entity.emergency;

public class EmergencyEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emgy_information.id
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emgy_information.scenic_id
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    private Integer scenicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emgy_information.title
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emgy_information.content
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emgy_information.author
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    private String author;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emgy_information.id
     *
     * @return the value of emgy_information.id
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emgy_information.id
     *
     * @param id the value for emgy_information.id
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emgy_information.scenic_id
     *
     * @return the value of emgy_information.scenic_id
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    public Integer getScenicId() {
        return scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emgy_information.scenic_id
     *
     * @param scenicId the value for emgy_information.scenic_id
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    public void setScenicId(Integer scenicId) {
        this.scenicId = scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emgy_information.title
     *
     * @return the value of emgy_information.title
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emgy_information.title
     *
     * @param title the value for emgy_information.title
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emgy_information.content
     *
     * @return the value of emgy_information.content
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emgy_information.content
     *
     * @param content the value for emgy_information.content
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emgy_information.author
     *
     * @return the value of emgy_information.author
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emgy_information.author
     *
     * @param author the value for emgy_information.author
     *
     * @mbggenerated Mon Sep 26 21:35:18 CST 2016
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }
}