package edu.ynu.travel.entity.emergency;

public class InfoEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.id
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info.content
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.id
     *
     * @return the value of info.id
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.id
     *
     * @param id the value for info.id
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info.content
     *
     * @return the value of info.content
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info.content
     *
     * @param content the value for info.content
     *
     * @mbggenerated Mon Sep 05 23:16:36 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}