package edu.ynu.travel.entity.ent;

import java.util.Date;

public class PerformEntity {

    private Integer id;

    private Integer scenicId;

    private String address;

    private String content;

    private String name;

    private Date startTime;

    private Date endTime;


    public Integer getId() {
        return id;
    }


    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_show_info.scenic_id
     *
     * @return the value of ent_show_info.scenic_id
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public Integer getScenicId() {
        return scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_show_info.scenic_id
     *
     * @param scenicId the value for ent_show_info.scenic_id
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public void setScenicId(Integer scenicId) {
        this.scenicId = scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_show_info.address
     *
     * @return the value of ent_show_info.address
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_show_info.address
     *
     * @param address the value for ent_show_info.address
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_show_info.content
     *
     * @return the value of ent_show_info.content
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_show_info.content
     *
     * @param content the value for ent_show_info.content
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_show_info.name
     *
     * @return the value of ent_show_info.name
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_show_info.name
     *
     * @param name the value for ent_show_info.name
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_show_info.start_time
     *
     * @return the value of ent_show_info.start_time
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_show_info.start_time
     *
     * @param startTime the value for ent_show_info.start_time
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ent_show_info.end_time
     *
     * @return the value of ent_show_info.end_time
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ent_show_info.end_time
     *
     * @param endTime the value for ent_show_info.end_time
     *
     * @mbggenerated Sun Sep 25 22:27:18 CST 2016
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}