package edu.ynu.travel.entity.canteen;

public class CanteenEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.id
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.scenic_id
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    private Integer scenicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.name
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.type
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canteen.price
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    private String price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.id
     *
     * @return the value of canteen.id
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.id
     *
     * @param id the value for canteen.id
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.scenic_id
     *
     * @return the value of canteen.scenic_id
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    public Integer getScenicId() {
        return scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.scenic_id
     *
     * @param scenicId the value for canteen.scenic_id
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    public void setScenicId(Integer scenicId) {
        this.scenicId = scenicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.name
     *
     * @return the value of canteen.name
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.name
     *
     * @param name the value for canteen.name
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.type
     *
     * @return the value of canteen.type
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.type
     *
     * @param type the value for canteen.type
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canteen.price
     *
     * @return the value of canteen.price
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canteen.price
     *
     * @param price the value for canteen.price
     *
     * @mbggenerated Mon Sep 26 14:31:14 CST 2016
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }
}