package edu.ynu.travel.mapper.user;

import edu.ynu.travel.entity.user.MenuEntity;
import org.springframework.stereotype.Repository;

@Repository("MenuMapper")
public interface MenuEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Sep 27 23:05:25 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Sep 27 23:05:25 CST 2016
     */
    int insert(MenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Sep 27 23:05:25 CST 2016
     */
    int insertSelective(MenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Sep 27 23:05:25 CST 2016
     */
    MenuEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Sep 27 23:05:25 CST 2016
     */
    int updateByPrimaryKeySelective(MenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu
     *
     * @mbggenerated Tue Sep 27 23:05:25 CST 2016
     */
    int updateByPrimaryKey(MenuEntity record);
}